version: "3.8"
services:
  database:
    image: postgres:15.1-alpine
    container_name: database
    restart: unless-stopped
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    env_file: .env
    volumes:
      - dbdata:/var/lib/postgresql/data
volumes:
  dbdata: